FROM node:20

# Proxy configuration for corporate network
ARG http_proxy
ARG https_proxy
ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Fix Vite's crypto problem
ENV NODE_OPTIONS=--experimental-global-webcrypto

# Fix permission denied problem
RUN chmod +x node_modules/.bin/vite

EXPOSE 5173

CMD ["npm", "run", "dev"]
