"""Add sys_event_log field to report table

Revision ID: 003
Revises: 002
Create Date: 2024-12-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding
    from alembic import context
    conn = context.get_bind()
    
    # Check if sys_event_log column exists
    result = conn.execute(sa.text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name='report' AND column_name='sys_event_log'
    """))
    
    if not result.fetchone():
        op.add_column('report', sa.Column('sys_event_log', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'sys_event_log')
    # ### end Alembic commands ###