"""Add cpu_codename field to report table

Revision ID: 004
Revises: 003
Create Date: 2024-12-23 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding
    from alembic import context
    conn = context.get_bind()
    
    # Check if cpu_codename column exists
    result = conn.execute(sa.text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name='report' AND column_name='cpu_codename'
    """))
    
    if not result.fetchone():
        op.add_column('report', sa.Column('cpu_codename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'cpu_codename')
    # ### end Alembic commands ###