"""Add comment field to report table

Revision ID: 005
Revises: 004
Create Date: 2024-12-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding
    from alembic import context
    conn = context.get_bind()
    
    # Check if comment column exists
    result = conn.execute(sa.text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name='report' AND column_name='comment'
    """))
    
    if not result.fetchone():
        op.add_column('report', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'comment')
    # ### end Alembic commands ###