"""Add music_type field to report table

Revision ID: 008
Revises: 007
Create Date: 2026-02-05 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008'
down_revision = '007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding
    from alembic import context
    conn = context.get_bind()
    
    # Check if music_type column exists
    result = conn.execute(sa.text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name='report' AND column_name='music_type'
    """))
    
    if not result.fetchone():
        op.add_column('report', sa.Column('music_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'music_type')
    # ### end Alembic commands ###
