"""Add short_scenario field to report table

Revision ID: 009
Revises: 008
Create Date: 2026-03-02 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009'
down_revision = '008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding
    from alembic import context
    conn = context.get_bind()
    
    # Check if short_scenario column exists
    result = conn.execute(sa.text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name='report' AND column_name='short_scenario'
    """))
    
    if not result.fetchone():
        op.add_column('report', sa.Column('short_scenario', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'short_scenario')
    # ### end Alembic commands ###
